# Generated by Django 2.2.7 on 2019-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='phones',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
