# Generated by Django 2.2.7 on 2019-11-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191113_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='email',
            field=models.CharField(default='  ', max_length=10),
            preserve_default=False,
        ),
    ]
