# Generated by Django 2.2.7 on 2019-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20191113_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='hobbies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='project_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='project_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
