# Generated by Django 2.2.7 on 2019-11-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20191113_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='address',
            field=models.TextField(blank=True, max_length=2047),
        ),
    ]
