# Generated by Django 2.2.7 on 2019-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resumeitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
